# Generated by Django 3.2 on 2021-06-13 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20210612_1929'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
    ]
