# Generated by Django 3.2 on 2021-09-11 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20210910_2325'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_page_url',
            field=models.CharField(default='amir', max_length=200),
            preserve_default=False,
        ),
    ]
