# Generated by Django 3.2 on 2021-10-07 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_alter_article_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='body_fa',
        ),
        migrations.RemoveField(
            model_name='article',
            name='desc_fa',
        ),
        migrations.RemoveField(
            model_name='article',
            name='title_fa',
        ),
        migrations.RemoveField(
            model_name='category',
            name='name_fa',
        ),
        migrations.AlterField(
            model_name='user',
            name='skills',
            field=models.CharField(help_text='pls separate the skills by 3', max_length=500, null=True),
        ),
    ]
